# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  pull_request:
    branches: [ development ]
  push:
    branches: [ main ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: PyInstaller Windows iRcorners
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
          spec: ircorners.spec

      - name: PyInstaller Windows Trackbuilder
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
          spec: trackbuilder.spec

      - name: Copy ressources/ folder
        run: cp -r src/ressources/ src/dist/windows/

      - name: Copy templates/ folder
        run: cp -r src/templates/ src/dist/windows/

      - name: Copy duplicates/ folder
        run: cp -r src/duplicates/ src/dist/windows/

      - uses: actions/upload-artifact@v2
        with:
          name: iRCorners
          path: src/dist/windows # or path/to/artifact
          
      - uses: actions/upload-artifact@v2
        with:
          name: iRCorners
          path: src/ircorners.cfg
